controller_frequency: 4.0
TrajectoryPlannerROS:

  holonomic_robot: false
  #max_vel_theta 0.5
  #acc_lim_theta 1.5
  #min_vel -0.3
  #oscillation_timeout 0.1
  max_vel_x: 0.35
  escape_vel: -0.2
  occdist_scale: 0.01
  pdist_scale: 0.8
  gdist_scale: 0.5
  #heading_lookahed 0.5
  #meter_scoring true
  #dwa true
  #heading_scoring true
  controller_frequency: 4.0